const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=process.argv[2];
const alertSource=fs.readFileSync(root+'/Dashboard/templates/alerts.html','utf8').replace(/\r\n/g,'\n');
const alertFunction=alertSource.slice(alertSource.indexOf('function countAlertAssets('),alertSource.indexOf('\nfunction refreshAlerts('));
const alertsContext={};vm.createContext(alertsContext);vm.runInContext(alertFunction,alertsContext);
assert.equal(alertsContext.countAlertAssets([{asset_id:1,ip:'127.0.0.1'},{asset_id:2,ip:'127.0.0.1'},{asset_id:1,ip:'127.0.0.1'}]),2);
assert.equal(alertsContext.countAlertAssets([{ip:'127.0.0.1',asset_port:502},{ip:'127.0.0.1',asset_port:5031}]),2);
const graphSource=fs.readFileSync(root+'/Dashboard/templates/attack_paths.html','utf8').replace(/\r\n/g,'\n');
const functions=graphSource.slice(graphSource.indexOf('function routeNodes('),graphSource.indexOf('function renderGraph('));
const context={GRAPH_EDGES:[['SCADA','HMI'],['RTU','SCADA'],['RTU','PLC'],['OTHER','UNREACHED']]};
vm.createContext(context);vm.runInContext(functions,context);
const links=context.buildGraphLinks([{path_json:'["HMI","SCADA","RTU","PLC"]'}]);
assert.deepEqual(links.filter(l=>l.onPath).map(l=>`${l.source}->${l.target}`),['HMI->SCADA','SCADA->RTU','RTU->PLC']);
assert(!links.some(l=>l.onPath&&l.source==='SCADA'&&l.target==='HMI'));
assert.equal(links.filter(l=>!l.onPath).length,1);
const both=context.buildGraphLinks([{path_json:['HMI','SCADA']},{path_json:['SCADA','HMI']}]);
assert.equal(both.filter(l=>l.onPath).length,2);
assert.equal(context.buildGraphLinks([{path_json:'bad json'}]).filter(l=>l.onPath).length,0);
console.log('Alert asset identity and ordered route-direction regressions passed.');
